version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: gateway_pagamentos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # porta que sua aplicação Java usa pra falar com o RabbitMQ
      - "15672:15672" # painel web de administração
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  pgdata: